"""
Build the final user-ready report from news_22apr_v4.xlsx.

Structure of the output:
  * stock_news sheet     -> one row per stock-focused news item (as-is)
  * industry_insights    -> for each industry with enough material, a
                            multi-bullet briefing (generated by LLM from
                            ALL items tagged with that industry, both
                            stock-focused and sector-only)
  * all_items_by_industry-> every item grouped by industry (long view)
  * overview             -> industry manifest (counts, insight yes/no)
  * README               -> short description of each sheet

Other fixes:
  * ftfy.fix_text() applied to every text cell (safety against mojibake)
  * CSV written with encoding='utf-8-sig' so Excel auto-detects UTF-8

Run:
  cd news_scratch
  .venv/bin/python build_final.py
  .venv/bin/python build_final.py --insight-threshold 5
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    import truststore  # type: ignore
    truststore.inject_into_ssl()
except Exception:
    pass

import ftfy
import pandas as pd
from dotenv import load_dotenv

HERE = Path(__file__).resolve().parent
for cand in [HERE / ".env", HERE.parent / "wesbiteBE" / ".env"]:
    if cand.exists():
        load_dotenv(cand)
        break

from openai import OpenAI  # noqa: E402

from add_stock_codes import insert_exchange_columns_after_stocks  # noqa: E402

API_KEY = os.environ.get("OPENAI_API_KEY")
if not API_KEY:
    sys.exit("ERROR: OPENAI_API_KEY is not set")
client = OpenAI(api_key=API_KEY)

PRICE_IN = {"gpt-4.1-nano": 0.10, "gpt-4.1-mini": 0.40}
PRICE_OUT = {"gpt-4.1-nano": 0.40, "gpt-4.1-mini": 1.60}

# ---------------------------------------------------------------------------
# Text cleanup
# ---------------------------------------------------------------------------
def clean(s: Any) -> Any:
    if not isinstance(s, str):
        return s
    return ftfy.fix_text(s)


def clean_df(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    for col in out.columns:
        if out[col].dtype == object:
            out[col] = out[col].apply(clean)
    return out


# ---------------------------------------------------------------------------
# Industry-insight LLM call
# ---------------------------------------------------------------------------
INSIGHT_SYSTEM_PROMPT = """You are preparing a daily industry briefing for \
Indian equity investors. You will receive N news items that have already \
been triaged as material for a SINGLE industry. Produce a tight, factual, \
user-facing insight for that industry for the day.

REQUIREMENTS:
  * headline       - ONE sentence capturing the dominant theme of the day \
for this industry. No hype. Preserve the most important number if possible.
  * bullets        - 4 to 8 BULLET POINTS, each 1-2 sentences. Each bullet \
must cover a DISTINCT event / theme / datapoint. MERGE items that are the \
same story. Preserve key numbers, company names, policy details, dates. \
Write in a direct, user-friendly voice. Include direction hints where useful \
(e.g. "could pressure margins", "likely tailwind for exporters"). For large \
industries with many items, use the upper end of the range (up to 8).
  * direction      - ONE of: positive | negative | neutral | mixed. Refers to \
the INDUSTRY'S net direction for the day.
  * key_numbers    - Comma-separated list of the most important numbers from \
across all items (values, percentages, dates).
  * key_stocks     - Comma-separated list of Indian LISTED companies that \
are movers today for this industry. Pull these only from the items you were \
given; do NOT add peers. Leave empty if none are individually actionable.
  * key_themes     - Comma-separated list of 2-5 theme tags \
(e.g. "west asia war, refining margins, crude supply").

STYLE:
  * Write as if sending to a paying retail investor. Factual. No fluff.
  * Numbers MUST be preserved (crore, lakh, percentages, dates).
  * No emojis. No adjectives like "exciting", "robust".
  * Do NOT invent items that aren't in the input.

Return a single JSON OBJECT with keys: headline, bullets (array of strings), \
direction, key_numbers, key_stocks, key_themes. No markdown, no prose \
outside the JSON.
"""


def _format_items_for_industry(industry: str, items: List[Dict[str, Any]]) -> str:
    lines = [f"INDUSTRY: {industry}", f"ITEMS ({len(items)}):"]
    for i, it in enumerate(items, 1):
        direction = it.get("direction") or ""
        stocks = it.get("affected_stocks") or ""
        numbers = it.get("key_numbers") or ""
        src = it.get("source") or ""
        pub = it.get("published_at_ist") or ""
        title = it.get("title") or ""
        summary = it.get("ai_summary") or ""
        implication = it.get("implication") or ""
        lines.append(
            f"\n[{i}] {title}\n"
            f"    source: {src}  time: {pub}  direction: {direction}\n"
            f"    stocks: {stocks}\n"
            f"    numbers: {numbers}\n"
            f"    summary: {summary}\n"
            f"    implication: {implication}"
        )
    return "\n".join(lines)


def _call_insight(
    model: str,
    industry: str,
    items: List[Dict[str, Any]],
    max_retries: int = 3,
) -> tuple[Dict[str, Any], int, int]:
    user_msg = _format_items_for_industry(industry, items)
    last_err: Optional[Exception] = None
    for attempt in range(max_retries):
        try:
            resp = client.chat.completions.create(
                model=model,
                temperature=0.1,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": INSIGHT_SYSTEM_PROMPT},
                    {"role": "user", "content": user_msg},
                ],
                max_tokens=1400,
            )
            content = resp.choices[0].message.content or "{}"
            data = json.loads(content)
            usage = resp.usage
            return (
                data,
                getattr(usage, "prompt_tokens", 0) or 0,
                getattr(usage, "completion_tokens", 0) or 0,
            )
        except Exception as e:
            last_err = e
            time.sleep(1.5 * (attempt + 1))
    raise RuntimeError(f"LLM failed after {max_retries} retries: {last_err}")


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------
def industries_of(s: str) -> List[str]:
    if not isinstance(s, str) or not s.strip():
        return []
    return [p.strip() for p in s.split(" | ") if p.strip()]


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default=str(HERE / "news_22apr_v4.xlsx"))
    ap.add_argument("--sheet", default="kept")
    ap.add_argument("--output", default=str(HERE / "news_22apr_final.xlsx"))
    ap.add_argument("--model", default="gpt-4.1-mini")
    ap.add_argument("--insight-threshold", type=int, default=5,
                    help="Generate industry insight only when an industry has "
                         ">= this many items (primary + secondary)")
    ap.add_argument("--workers", type=int, default=5)
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    in_path = Path(args.input)
    out_path = Path(args.output)
    if not in_path.exists():
        print(f"ERROR: {in_path} not found")
        return 1

    df = pd.read_excel(in_path, sheet_name=args.sheet).fillna("")
    df = clean_df(df)
    df = df.reset_index(drop=True)
    df["n_focal_stocks"] = pd.to_numeric(
        df.get("n_focal_stocks", 0), errors="coerce"
    ).fillna(0).astype(int)
    print(f"Loaded {len(df)} cleaned rows from {in_path.name}::{args.sheet}")

    # Build per-industry item pools (item can appear under multiple industries
    # if it has secondary tags).
    df["_all_industries"] = df["affected_industries"].apply(industries_of)
    # Fallback: if primary is present but not in affected_industries list
    # (should not happen, but just in case), add it.
    def _ensure(r):
        ind_list = list(r["_all_industries"])
        prim = str(r.get("industry_primary") or "").strip()
        if prim and prim not in ind_list:
            ind_list = [prim] + ind_list
        return ind_list
    df["_all_industries"] = df.apply(_ensure, axis=1)

    industry_to_rows: Dict[str, List[int]] = {}
    for i, inds in enumerate(df["_all_industries"]):
        for ind in inds:
            industry_to_rows.setdefault(ind, []).append(i)

    # Industries sorted by size
    industry_sizes = sorted(
        industry_to_rows.items(), key=lambda kv: len(kv[1]), reverse=True
    )
    print(f"\nIndustry item counts (primary + secondary):")
    for ind, rows in industry_sizes:
        mark = "*" if len(rows) >= args.insight_threshold else " "
        print(f"  {mark} {ind:46s} {len(rows):>3}")
    print(f"\n* = will get multi-bullet insight "
          f"(>= {args.insight_threshold} items)")

    # Call LLM for each qualifying industry in parallel
    big_industries = [
        (ind, rows) for ind, rows in industry_sizes
        if len(rows) >= args.insight_threshold
    ]
    small_industries = [
        (ind, rows) for ind, rows in industry_sizes
        if len(rows) < args.insight_threshold
    ]
    print(f"\nGenerating insights for {len(big_industries)} industries with "
          f"{args.model}...")

    t0 = time.time()
    insight_rows: List[Dict[str, Any]] = []
    tot_in = 0
    tot_out = 0

    def _run_industry(ind: str, row_ids: List[int]) -> Dict[str, Any]:
        items = df.iloc[row_ids].to_dict("records")
        data, ti, to = _call_insight(args.model, ind, items)
        return {
            "industry": ind,
            "n_items": len(items),
            "headline": str(data.get("headline") or "").strip(),
            "direction": str(data.get("direction") or "").strip().lower(),
            "bullets": [str(b).strip() for b in (data.get("bullets") or []) if str(b).strip()],
            "key_numbers": str(data.get("key_numbers") or "").strip(),
            "key_stocks": str(data.get("key_stocks") or "").strip(),
            "key_themes": str(data.get("key_themes") or "").strip(),
            "_tok_in": ti,
            "_tok_out": to,
        }

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futs = {pool.submit(_run_industry, ind, rows): ind
                for ind, rows in big_industries}
        for fut in as_completed(futs):
            ind = futs[fut]
            try:
                res = fut.result()
                insight_rows.append(res)
                tot_in += res.pop("_tok_in")
                tot_out += res.pop("_tok_out")
                print(f"  ok {ind:46s} bullets={len(res['bullets'])}")
            except Exception as e:
                print(f"  ERR {ind}: {e}")

    # Sort insight_rows by n_items desc
    insight_rows.sort(key=lambda r: r["n_items"], reverse=True)

    # For small industries, no LLM insight — just list their items later.
    # But do put them in the overview.
    for ind, rows in small_industries:
        insight_rows.append({
            "industry": ind,
            "n_items": len(rows),
            "headline": "",
            "direction": "",
            "bullets": [],
            "key_numbers": "",
            "key_stocks": "",
            "key_themes": "",
        })

    # ------------------------------------------------------------------
    # Build output frames
    # ------------------------------------------------------------------
    stock_news = df[df["n_focal_stocks"] >= 1].copy()
    stock_cols = [
        "affected_stocks", "score", "direction",
        "industry_primary", "affected_industries",
        "ai_summary", "implication", "key_numbers",
        "category", "source", "published_at_ist", "title", "link",
    ]
    stock_cols = [c for c in stock_cols if c in stock_news.columns]
    stock_news = stock_news[stock_cols].sort_values(
        ["affected_stocks", "score"], ascending=[True, False]
    ).reset_index(drop=True)

    print("\nEnriching stock rows with BSE/NSE/ISIN + market cap "
          "(Indian API + Yahoo + company_master fallback)…")
    stock_news = insert_exchange_columns_after_stocks(
        stock_news, progress_label="stock_news", progress_every=5
    )

    # Industry insights table: one row per industry.
    # Serialize bullets as newline-joined strings so the Excel cell is readable.
    insight_df_rows = []
    for ir in insight_rows:
        bullets = ir["bullets"] or []
        bullets_str = "\n".join(f"• {b}" for b in bullets)
        insight_df_rows.append({
            "industry": ir["industry"],
            "n_items": ir["n_items"],
            "direction": ir["direction"],
            "headline": ir["headline"],
            "bullets": bullets_str,
            "key_numbers": ir["key_numbers"],
            "key_stocks": ir["key_stocks"],
            "key_themes": ir["key_themes"],
        })
    insight_df = pd.DataFrame(insight_df_rows)
    insight_df_full = insight_df[insight_df["n_items"] >= args.insight_threshold]
    insight_df_small = insight_df[insight_df["n_items"] < args.insight_threshold]

    # all_items_by_industry: list every item under its primary industry, sorted.
    all_by = df.copy()
    all_by_cols = [
        "industry_primary", "affected_stocks", "score", "direction",
        "category", "ai_summary", "implication", "key_numbers",
        "source", "published_at_ist", "title", "link",
    ]
    all_by_cols = [c for c in all_by_cols if c in all_by.columns]
    all_by = all_by[all_by_cols].sort_values(
        ["industry_primary", "score", "published_at_ist"],
        ascending=[True, False, False],
    ).reset_index(drop=True)

    all_by = insert_exchange_columns_after_stocks(
        all_by, progress_label="all_items_by_industry", progress_every=25
    )

    # Overview: per-industry manifest
    overview_rows = []
    for ir in insight_rows:
        overview_rows.append({
            "industry": ir["industry"],
            "n_items": ir["n_items"],
            "has_insight": "yes" if ir["headline"] else "no",
            "direction": ir["direction"],
            "headline": ir["headline"] or "(below threshold – see all_items_by_industry)",
        })
    overview_df = pd.DataFrame(overview_rows)

    # Stats
    total_cost = (
        tot_in / 1_000_000 * PRICE_IN.get(args.model, 0.0)
        + tot_out / 1_000_000 * PRICE_OUT.get(args.model, 0.0)
    )
    stats = pd.DataFrame([
        {"metric": "source_file", "value": in_path.name},
        {"metric": "rows_total", "value": int(len(df))},
        {"metric": "rows_with_focal_stock", "value": int(len(stock_news))},
        {"metric": "rows_sector_only", "value": int((df["n_focal_stocks"] == 0).sum())},
        {"metric": "industries_total", "value": int(len(insight_rows))},
        {"metric": "industries_with_insight", "value": int(len(big_industries))},
        {"metric": "insight_threshold", "value": int(args.insight_threshold)},
        {"metric": "model", "value": args.model},
        {"metric": "input_tokens", "value": tot_in},
        {"metric": "output_tokens", "value": tot_out},
        {"metric": "estimated_cost_usd", "value": f"${total_cost:.4f}"},
        {"metric": "elapsed_sec", "value": round(time.time() - t0, 1)},
    ])

    readme = pd.DataFrame([
        {"sheet": "overview",
         "description": "Per-industry manifest: item count, whether a bullet insight was generated, and the day's headline for that industry."},
        {"sheet": "industry_insights",
         "description": "For industries above the threshold: the multi-bullet briefing for the day. "
                        "`bullets` cell contains 4–8 bullets separated by newlines. Use Wrap Text in Excel to read cleanly."},
        {"sheet": "industry_small",
         "description": "Industries below the insight threshold, listed for completeness. "
                        "No LLM bullets — see all_items_by_industry for the underlying stories."},
        {"sheet": "stock_news",
         "description": "Every item that is about one (or two) specific Indian listed stocks. "
                        "Earnings and order-wins have been removed upstream. "
                        "Columns after affected_stocks: bse_scrip_code, nse_symbol, isin, market_cap_cr "
                        "(resolved via Indian API with Yahoo + company_master fallbacks). "
                        "Use this as a 'stock news' feed outside of your separate financial-results pipeline."},
        {"sheet": "all_items_by_industry",
         "description": "Full view of every item grouped by primary industry. "
                        "Stock rows include the same BSE/NSE/ISIN/market-cap enrichment as stock_news. "
                        "Use this to drill into the bullets."},
        {"sheet": "run_stats",
         "description": "Token usage, cost, counts."},
        {"sheet": "README",
         "description": "This sheet."},
    ])

    with pd.ExcelWriter(out_path, engine="openpyxl") as xw:
        readme.to_excel(xw, sheet_name="README", index=False)
        overview_df.to_excel(xw, sheet_name="overview", index=False)
        insight_df_full.to_excel(xw, sheet_name="industry_insights", index=False)
        insight_df_small.to_excel(xw, sheet_name="industry_small", index=False)
        stock_news.to_excel(xw, sheet_name="stock_news", index=False)
        all_by.to_excel(xw, sheet_name="all_items_by_industry", index=False)
        stats.to_excel(xw, sheet_name="run_stats", index=False)

    # Enable wrap-text on the bullets cell so the sheet is readable
    try:
        from openpyxl import load_workbook
        from openpyxl.styles import Alignment
        wb = load_workbook(out_path)
        for sheet_name in ("industry_insights", "industry_small"):
            if sheet_name not in wb.sheetnames:
                continue
            ws = wb[sheet_name]
            header = [c.value for c in ws[1]]
            if "bullets" in header:
                col_idx = header.index("bullets") + 1
                for row in ws.iter_rows(min_row=2, min_col=col_idx,
                                        max_col=col_idx):
                    for cell in row:
                        cell.alignment = Alignment(wrap_text=True,
                                                   vertical="top")
                ws.column_dimensions[ws.cell(row=1, column=col_idx).column_letter].width = 95
            # Make headline / industry readable too
            for col_name, width in [("industry", 42), ("headline", 70),
                                    ("key_numbers", 40), ("key_stocks", 40),
                                    ("key_themes", 40), ("direction", 12),
                                    ("n_items", 10)]:
                if col_name in header:
                    idx = header.index(col_name) + 1
                    letter = ws.cell(row=1, column=idx).column_letter
                    ws.column_dimensions[letter].width = width
            ws.row_dimensions[1].height = 20
            for r_idx in range(2, ws.max_row + 1):
                ws.row_dimensions[r_idx].height = None  # let auto-fit
        wb.save(out_path)
    except Exception as e:
        print(f"  (warn) could not apply wrap-text formatting: {e}")

    # CSVs written with UTF-8-BOM so Excel opens them without mojibake
    stock_news.to_csv(out_path.with_name("news_22apr_final_stock_news.csv"),
                       index=False, encoding="utf-8-sig")
    insight_df_full.to_csv(out_path.with_name("news_22apr_final_industry_insights.csv"),
                           index=False, encoding="utf-8-sig")
    all_by.to_csv(out_path.with_name("news_22apr_final_all_items.csv"),
                   index=False, encoding="utf-8-sig")

    # --------------------------------------------------------------
    # Console report
    # --------------------------------------------------------------
    print()
    print("=" * 60)
    print(f"Final file: {out_path.name}")
    print(f"  rows_total                    : {len(df)}")
    print(f"  stock_news (focal stock set)  : {len(stock_news)}")
    print(f"  industry_insights generated   : {len(big_industries)}")
    print(f"  small industries listed       : {len(small_industries)}")
    print(f"Model : {args.model}")
    print(f"Tokens: in={tot_in:,}  out={tot_out:,}  cost=${total_cost:.4f}")
    print(f"Elapsed: {time.time() - t0:.1f}s")
    print()
    print("Industry insights preview:")
    for ir in insight_rows[:5]:
        if not ir["headline"]:
            continue
        print(f"\n  {ir['industry']}  ({ir['n_items']} items, {ir['direction']})")
        print(f"    HEADLINE: {ir['headline']}")
        for b in ir["bullets"][:3]:
            print(f"      • {b[:130]}")
        if len(ir["bullets"]) > 3:
            print(f"      … ({len(ir['bullets']) - 3} more bullets)")
    print()
    print(f"Wrote:")
    print(f"  {out_path}")
    print(f"  {out_path.with_name('news_22apr_final_stock_news.csv')}")
    print(f"  {out_path.with_name('news_22apr_final_industry_insights.csv')}")
    print(f"  {out_path.with_name('news_22apr_final_all_items.csv')}")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
